### ISSUE TITLE
dns_do not working

### ISSUE THREAD

**Issue by Ruffythemonkey** [seidler2547/acme.sh#1]
Hi the dnsapi dns_do is not working, i can not log in !

Authentication failed, are DO_PID and DO_PW set correctly? 

The DO_PID and DO_PW is correctly set as env.

**Comment by seidler2547** [comment]
Are you using your reseller credentials? `dns_do` does not work for "normal" DO customers, because only resellers have access to the API.

**Comment by Ruffythemonkey** [comment]
okay thanks for the info i am a nativ DO user.
